apiVersion: v1
kind: Pod
metadata:
    name: javawebapppod
    labels:
       app: javawebapp
spec:
   containers:
   - name: javawebappcontainer
     image: deba9853/mavenwebapp
     ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
       name: javawebappsvc
spec:
        type: NodePort
        selector:
                app: javawebapp
        ports:
        - port: 80
          targetPort: 8080
---
